version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto11
        commands:
            - npm install
    pre_build:
        commands:
            - echo Installing on `date`
            - npm run unit
    build:
        commands:
            - echo Build started on `date`
            - npm run build
    post_build:
        commands:
            - echo Build completed on `date`
            
artifacts:
    files:
        - '**/*'
    base-directory: 'build'